services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\HideRecordsDeletedDifferently\:
    resource: '../../../Classes/Features/HideRecordsDeletedDifferently/*'

  In2code\In2publishCore\Features\HideRecordsDeletedDifferently\EventListener\HideRecordsDeletedDifferentlyEventListener:
    tags:
      - name: in2publish_core.conditional.event.listener
        condition: 'CONF:features.hideRecordsDeletedDifferently.enable'
        identifier: 'in2publish-HideRecordsDeletedDifferently-DecideIfRecordShouldBeIgnored'
        method: 'decideIfRecordShouldBeIgnored'
        event: In2code\In2publishCore\Event\DecideIfRecordShouldBeIgnored
