services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $localDatabase: '@In2code.In2publishCore.Database.Local'

  In2code\In2publishCore\Features\RedirectsSupport\:
    resource: '../../../Classes/Features/RedirectsSupport/*'

  In2code\In2publishCore\Features\RedirectsSupport\DataProvider\ForeignSiteIdentifierItemProcFunc:
    public: true
