services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\LogPublishingEvents\:
    resource: '../../../Classes/Features/LogPublishingEvents/*'

  In2code\In2publishCore\Features\LogPublishingEvents\EventListener\PublishEventLogger:
    tags:
      - name: event.listener
        identifier: in2publishcore-publisheventlogger-recursiverecordpublishingbegan
        method: whenRecursiveRecordPublishingBegan
        event: In2code\In2publishCore\Event\RecursiveRecordPublishingBegan
