services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\ConditionalEventListener\:
    resource: '../../../Classes/Features/ConditionalEventListener/*'
