services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\RecordBreadcrumbs\:
    resource: '../../../Classes/Features/RecordBreadcrumbs/*'
    exclude:
      - '../../../Classes/Features/RecordBreadcrumbs/Domain/Extensions/*'
