services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\RefIndexUpdate\:
    resource: '../../../Classes/Features/RefIndexUpdate/*'

  In2code\In2publishCore\Features\RefIndexUpdate\Domain\Anomaly\RefIndexUpdater:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-RefIndexUpdater-RecordWasPublished'
        method: 'registerRefIndexUpdate'
        event: In2code\In2publishCore\Event\RecordWasPublished
      - name: event.listener
        identifier: 'in2publishcore-RefIndexUpdater-RecursiveRecordPublishingEnded'
        method: 'writeRefIndexUpdateTask'
        event: In2code\In2publishCore\Event\RecursiveRecordPublishingEnded
