services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\In2publishCore\Features\ResolveFilesForIndices\:
    resource: '../../../Classes/Features/ResolveFilesForIndices/*'

  In2code\In2publishCore\Features\ResolveFilesForIndices\EventListener\FileRecordListener:
    tags:
      - name: event.listener
        identifier: 'in2publishcore-FileRecordListener-RecordWasCreated'
        method: 'onRecordWasCreated'
        event: In2code\In2publishCore\Event\RecordWasCreated
      - name: event.listener
        identifier: 'in2publishcore-FileRecordListener-RecordRelationsWereResolved'
        method: 'onRecordRelationsWereResolved'
        event: In2code\In2publishCore\Event\RecordRelationsWereResolved
