services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $databaseOfForeign: '@=service("In2code\\In2publishCore\\Factory\\ConnectionFactory").createOtherConnection()'

  In2code\In2publishCore\Component\PostPublishTaskExecution\:
    resource: '../../../Classes/Component/PostPublishTaskExecution/*'
    exclude:
      - '../../../Classes/Component/PostPublishTaskExecution/Command/Foreign/*'

  In2code\In2publishCore\Component\PostPublishTaskExecution\Service\TaskExecutionService:
    public: true

  In2code\In2publishCore\Component\PostPublishTaskExecution\Domain\Repository\TaskRepository:
    public: true
